<?php

/**
 * @file
 * Module implementing accordion functionality in paragraphs when editing.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Helper function to check if a string ends with another string.
 */
function ends_with($haystack, $needle) {
  $length = strlen($needle);

  return $length === 0 ||
    (substr($haystack, -$length) === $needle);
}

/**
 * Implements hook_form_alter().
 */
function suopa_paragraph_accordion_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (ends_with($form_id, '_edit_form')) {
    $form['#attached']['library'][] = 'suopa_paragraph_accordion/paragraph-accordion';
    
    if (array_key_exists('field_paragraphs', $form) && array_key_exists('widget', $form['field_paragraphs'])) {
      foreach ($form['field_paragraphs']['widget'] as &$item) {
        if (is_array($item) && array_key_exists('subform', $item) && array_key_exists('#type', $item) && $item['#type'] == 'container') {
          array_push($item['subform']['#attributes']['class'], 'paragraph-accordion-panel');
        }
      }
    }
  }
}
