version: '3.7'

services:

  app:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: "${DRUPAL_IMAGE}"
    volumes:
      - .:/app:delegated
      - ssh:/tmp/druid_ssh-agent:ro
    environment:
      APP_ENV: "${APP_ENV:-dev}"
      DRUPAL_ROUTES: "https://varnish-${DRUPAL_HOSTNAME}"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
      #XDEBUG_ENABLE: "true"
      #XDEBUG_CONFIG: "remote_port=9001 remote_host=host.docker.internal remote_connect_back=0"
      SIMPLETEST_BASE_URL: "http://app:8080"
      SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
    networks:
      - internal
      - stonehenge-network
    labels:
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: "Host:${DRUPAL_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https

  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: druidfi/db:mysql5.7-drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal

  varnish:
    container_name: "${COMPOSE_PROJECT_NAME}-varnish"
    image: druidfi/varnish:6-drupal
    depends_on:
      - app
    networks:
      - internal
      - stonehenge-network
    labels:
      traefik.enable: true
      traefik.port: 6081
      traefik.frontend.rule: "Host:varnish-${DRUPAL_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https

networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  db_data:
  ssh:
    name: stonehenge-ssh
    external: true
