version: '3.7'

services:

  drupal:
    hostname: &hostname "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-drupal"
    image: "${DRUPAL_IMAGE}"
    environment:
      # If you want to use stage_file_proxy, uncomment following line and add the production url of your website:
      #AMAZEEIO_PRODUCTION_URL: 'http://www.mysite.fi'
      # APC Support is by default enabled, but in some cases it can make issues, change to 0 to disable:
      APC: 1
      VIRTUAL_HOST: *hostname
      WEBROOT: "${DRUPAL_WEBROOT}"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}" # Site URI for Drush 9
      XDEBUG_CONFIG: "remote_port=9001 remote_host=host.docker.internal remote_connect_back=0"
    volumes:
    - .:/var/www/drupal/public_html:delegated
    - ssh:/tmp/amazeeio_ssh-agent
    ports:
    - "3306"
    networks:
    - dev-network
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:${DRUPAL_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https

networks:
  dev-network:
    name: stonehenge-network
    external: true

volumes:
  ssh:
    name: stonehenge-ssh
    external: true
