<?php

/**
 * @file
 * Contains suopa_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function suopa_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the suopa_events module.
    case 'help.page.suopa_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event entity type and related functionalities for Suomidigi.fi') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function suopa_events_theme() {
  return [
    'contact_information' => [
      'variables' => [
        'name' => NULL,
        'email' => NULL,
        'phone_number' => NULL,
      ],
    ],
    'suopa_back_to_events' => [
      'variables' => [
        'url' => NULL,
        'link_title' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function suopa_events_theme_suggestions_contact_information_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'contact_information';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function suopa_events_form_node_form_alter(&$form, &$form_state, $form_id) {
  /* @var Drupal\Core\Entity\FieldableEntityInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  if ($node->getType() == 'event') {
    // Prevent access to certain fields if user doesn't have permission.
    $user = \Drupal::currentUser();
    if (!$user->hasPermission('access suomidigi events')) {
      $form['field_event_image']['#access'] = FALSE;
      $form['field_venue_description']['#access'] = FALSE;
      $form['field_event_org_contact_info']['#access'] = FALSE;
      $form['field_event_free_text']['#access'] = FALSE;
      $form['field_approved']['#access'] = FALSE;
    }
  }
}
