<?php

/**
 * @file
 * Contains suopa_feed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function suopa_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the suopa_feed module.
    case 'help.page.suopa_feed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hosts all feed related custom code.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function suopa_feed_theme() {
  return [
    'suopa_feed_wrapper' => [
      'variables' => [
        'id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * {@inheritdoc}
 */
function suopa_feed_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->getType() != 'feed') {
    return;
  }

  $variables['id'] = [
    '#markup' => $paragraph->id(),
  ];

  return;

  /*foreach ($terms as $term) {
    // Fetch all potential legislation card collections from the selected
    // terms. Note that all the child terms are not necessarily collections!
    $cardCollectionTerms = Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->getChildren($term);
    foreach ($cardCollectionTerms as $collectionTerm) {
      $cards = suopa_legislations_get_related_legislation_cards($collectionTerm, $langcode);
      if (!count($cards)) {
        continue;
      }

      if ($collectionTerm->hasTranslation($langcode)) {
        $collectionLabel = $collectionTerm->getTranslation($langcode)->getName();
      }
      else {
        $collectionLabel = $collectionTerm->getName();
      }

      $renderedLegislationCollection = [
        'title' => [
          '#theme' => 'suopa_legislations_collection_label',
          '#collection_label' => $collectionLabel,
        ],
        'cards' => [
          '#theme' => 'suopa_legislations_collection',
          '#collection' => $cards,
          '#attached' => [
            'library' => [
              'suopa_legislations/expanding-panel',
            ],
          ],
        ],
      ];

      $variables['legislation_collections'][] = $renderedLegislationCollection;
    }
  }*/
}
