<?php

/**
 * @file
 * Contains suopa_editorial.module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * {@inheritdoc}
 */
function suopa_editorial_form_alter(&$form, $form_state) {
  suopa_editorial_modify_article_publishing_info($form, $form_state);
  $form['#attached']['library'][] = 'suopa_editorial/paragraph-drag-n-drop';
}

/**
 * Modify publishing options in article node forms.
 *
 * Mainly move the publishing info fields to the left sidebar.
 *
 * @param array $form
 *   Form.
 * @param array $form_state
 *   Form state.
 */
function suopa_editorial_modify_article_publishing_info(&$form, $form_state) {
  $allowedIds = ['node_article_edit_form', 'node_article_form'];

  if (!in_array($form['#form_id'], $allowedIds)) {
    return;
  }

  // $form['published_at']['widget'][0]['#title'] = t('Displayed publish time');

  $form['field_displayed_update_time']['#group'] = 'revision_information';
  // $form['field_displayed_update_time']['#weight'] = 20;

  $form['field_displayed_author']['#group'] = 'revision_information';
  // $form['field_displayed_author']['#weight'] = 21;
}

/**
 * Implements hook_views_pre_render().
 *
 * Modify media entity browser image width to suit smaller screens.
 *
 * {@inheritDoc}
 */
function suopa_editorial_views_pre_render(ViewExecutable $view) {
  if (isset($view) && $view->id() === 'media_entity_browser') {
    $view->element['#attached']['library'][] = 'suopa_editorial/media-entity-browser';
  }
}
