_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: suomidigi
defaults:
  sender: swiftmailer
  formatter: swiftmailer
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
  webform: {  }
  content_moderation_notifications:
    none:
      sender: swiftmailer
      formatter: swiftmailer
