theme: suomidigi
defaults:
  sender: swiftmailer
  formatter: swiftmailer
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: swiftmailer
      sender: swiftmailer
  webform: {  }
  content_moderation_notifications:
    none:
      formatter: swiftmailer
      sender: swiftmailer
