vocabularies:
  legislation: true
  tags: false
  article_type: false
override_taxonomy_page: true
show_links_on_node: true
link_to_ordering_page: true
link_to_ordering_page_taxonomy_admin: true
_core:
  default_config_hash: o7HVlN4HeLv0HwjM_P8slB6MW4W80jB2_eBqRZjwYeg
