user_never_lastlogin_value: '3'
user_never_lastlogin_period: year
user_lastlogin_value: '3'
user_lastlogin_period: year
user_inactive_value: ''
user_inactive_period: days
user_blocked_value: ''
user_blocked_period: days
enabled_never_loggedin_users: 1
enabled_loggedin_users: 1
enabled_inactive_users: 0
enabled_blocked_users: 0
purge_users_roles:
  authenticated: authenticated
  content_producer: content_producer
  group_member: group_member
  editor_in_chief: 0
  administrator: 0
  webform_administrator: 0
  group_administrator: 0
  groups_administrator: 0
  user_administrator: 0
purge_on_cron: 0
inactive_user_notify_text: "Dear User, \r\n\r\nYour account has been deleted due the website’s policy to automatically remove users who match certain criteria. If you have concerns regarding the deletion, please talk to the administrator of the website. \r\n\r\nThank you"
send_email_notification: 0
purge_user_cancel_method: user_cancel_delete
